### ISSUE TITLE
When closing a protected notebook, unwanted warning dialog comes up

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/radiopadre#19]
By design, we can't save changes to protected notebooks. Yet, when trying to close one that's "dirty", the browser pops up the "changes will be lost" dialog anyway. Happens via here: 

https://github.com/ipython/ipython/blob/2.x/IPython/html/static/notebook/js/notebook.js#L172

and can probably be defeated by wrapping another ``onbeforeunload`` handler around this.

**Comment by gijzelaerr** [comment]
I don't think hacking and monkey patching the IPython internals is a good idea, this may change in the next release.

Usually it is a very bad idea to fight a common workflow.

**Comment by o-smirnov** [comment]
I'm wrapping, not patching. :) I'm agree about the dangers, but some things are just too annoying, so some very minimal hacking is ok I think.
