### ISSUE TITLE
need quick access to sorted subdirectories

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/radiopadre#6]
A common use case is something like, get me the most-recently modified directory called "reduction-*", and make a DirList from that. Should be easy to incorporate this elegantly, since a DirList is already a list of directories, and already has sorting facilities (although DirList is always recursive, so also need an option to make it non-recursive).

Perhaps something like:

```
from radiopadre import lsd, lsdr
lsd(pattern="*")     # equivalent to DirList('.',recursive=False)(pattern)
lsdr(pattern="*")    # equivalent to DirList('.',recursive=True)(pattern)
```

The function names are chosen to be reminiscent of  ``ls -d`` and ``ls -dR``. Also, when else do I get a chance to import LSD from a Padre?

Then the use case above is

```
lsd("reduction-*").sort("t")[-1]     # sort by time and get last entry
```

or even with an explicit "alias":

```
lsd("reduction-*").latest()       # since it's such a common use case
```

**Comment by gijzelaerr** [comment]
I see options for a new naming schema for when we run out of cats

**Comment by o-smirnov** [comment]
OK, done. Defined ``radiopadre.lsd()``, ``lsdr()`` and ``latest()``.
